### ISSUE TITLE
suggestion: getLocation

### ISSUE THREAD

**Issue by hunyan-io** [Lautenschlager-id/Fromage#1]
getLocation(community, section)
>returns f and s

**Comment by Lautenschlager-id** [comment]
**Client:getTopic** will be added soon and it'll come with the **f** and **s** values!

**Comment by Lautenschlager-id** [comment]
This suggestion is great.

I have added enumerations for this.
`enumerations.location.en.transformice.modules`
`enumerations.location.xx.atelier801.announcements`

And the function itself,
`self.getLocation(forum, community, section)`
